### ISSUE TITLE
Uncaught exception thrown by finalizer

### ISSUE THREAD

**Issue by ghost** [RobertZagorski/NetworkStats#6]
when i get stats for all packages which has internet permission i get this error many times!

Uncaught exception thrown by finalizer
and
 java.lang.IllegalStateException: Binder has been finalized!
              at android.os.BinderProxy.transactNative(Native Method)
              at android.os.BinderProxy.transact(Binder.java:503)
              at android.net.INetworkStatsSession$Stub$Proxy.close(INetworkStatsSession.java:463)
              at android.app.usage.NetworkStats.close(NetworkStats.java:297)
              at android.app.usage.NetworkStats.finalize(NetworkStats.java:110)
              at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:217)
              at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:200)
              at java.lang.Thread.run(Thread.java:818)

**Comment by Nethki** [comment]
Same issue here
java.lang.IllegalStateException: Binder has been finalized!
                                                                at android.os.BinderProxy.transactNative(Native Method)
                                                                at android.os.BinderProxy.transact(Binder.java:617)
                                                                at android.net.INetworkStatsSession$Stub$Proxy.close(INetworkStatsSession.java:462)
                                                                at android.app.usage.NetworkStats.close(NetworkStats.java:382)
                                                                at android.app.usage.NetworkStats.finalize(NetworkStats.java:118)
                                                                at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222)
                                                                at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209)
                                                                at java.lang.Thread.run(Thread.java:776)

**Comment by RobertZagorski** [comment]
Well, internal classes of Android system responsible for NetworkStats throw it:
https://github.com/simhacks/android_platform_frameworks_base/blob/master/core/java/com/android/internal/net/NetworkStatsFactory.java#L177

**Comment by shailesh-mota** [comment]
Exception can occur if the caller doesn't call `NetworkStats.close()` on the instance of `NetworkStats`. Calling close appropriately on all the referenced instances of `NetworkStats` can fix this Binder crashes.

**Comment by RobertZagorski** [comment]
As per above comment this is internal issue of NetworkStats and solution is given.
